---
- name: Get CLI alias
  ansible.builtin.uri:
    url: "{{ baseurl }}/system/cli_aliases/%2A"
    method: get
    headers:
      Cookie: "{{ login.cookies_string }}"
    status_code: 
      - 200
      - 404
    validate_certs: false
  register: get_alias
  delegate_to: localhost
  ignore_errors: true

- name: Remove json key from get_alias
  ansible.builtin.set_fact:
    get_alias: "{{ get_alias.json | default({}) }}"