username: "{{ lookup('env', 'ARUBA_LOCAL_USER') }}"
password: "{{ lookup('env', 'ARUBA_LOCAL_USER_PASSWORD') }}"
ospf_key_1: "{{ lookup('env', 'ARUBA_OSPF_KEY_1') }}"
bgp_key: "{{ lookup('env', 'ARUBA_BGP_KEY') }}"
tacacs_key: "{{ lookup('env', 'ARUBA_TACACS_KEY') }}"
cak_key_1: "{{ lookup('env', 'ARUBA_CAK_KEY_1') }}"
ckn_key_1: "{{ lookup('env', 'ARUBA_CKN_KEY_1') }}"
snmp_community: "{{ lookup('env', 'ARUBA_SNMP_COMMUNITY') }}"