username: "{{ lookup('env', 'ARUBA_LOCAL_USER') }}"
password: "{{ lookup('env', 'ARUBA_LOCAL_USER_PASSWORD') }}"
ospf_key_1: "{{ lookup('env', 'ARUBA_OSPF_KEY_1') }}"
bgp_key: "{{ lookup('env', 'ARUBA_BGP_KEY') }}"