---
time:
  timezone: europe/stockholm
  ntp:
    dhcp_enable: false
    enable: true
    vrf: mgmt
    servers:
      1.1.1.1:
        minpoll: 6
        maxpoll: 10
        burst_mode: iburst
        prefer: false
      2.2.2.2:
        minpoll: 4
        maxpoll: 4
        burst_mode: iburst
        prefer: false
        version: 4