# ---
# keychain_schema:
#   name:
#     required: True

# keychain_mapped_attributes:
#   name:

# key_schema:
#   key_id: 
#     required: True
#   key_string:
#   cryptographic_algorithm:
#     default: md5

# key_mapped_attributes:
#   auth_key:
#   auth_type: