---
- name: Get syslog remotes
  ansible.builtin.uri:
    url: "{{ baseurl }}/system/syslog_remotes/%2A?selector=writable"
    method: get
    headers:
      Cookie: "{{ login.cookies_string }}"
    status_code: 
      - 200
      - 404
    validate_certs: false
  register: get_syslog_remotes
  delegate_to: localhost
  ignore_errors: true

- name: Remove json key
  ansible.builtin.set_fact:
    get_syslog_remotes: "{{ get_syslog_remotes.json | default({}) }}"